name: Test on browsers beta versiom
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    steps:
    - name: Install Firefox beta
       uses: browser-actions/setup-firefox@latest
       with:
         firefox-version: 'latest-beta' #latest-devedition
    - name: Install Chrome beta 
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: beta
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Browser versions
      run: |
        google-chrome --version
        firefox --version
    - name: Run unit tests
      run: npm test
    - name: Run tests on Chrome beta
      run: bin/sitespeed.js -b chrome -n 1 --xvfb https://www.sitespeed.io
    - name: Run tests on Firefox beta
      run: bin/sitespeed.js -b firefox -n 1 --xvfb https://www.sitespeed.io
